services:
  dinkum-online-api:
    container_name: dinkum-online-api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/usr/src/api/
    depends_on:
      - dinkum-online-db

  dinkum-online-db:
    image: mongo
    container_name: dinkum-online-db
    ports:
      - "${DB_PORT}:27017"
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./dbdata/:/data/db
      - ./init-mongodb:/docker-entrypoint-initdb.d
