services:
  dinkum-online-api:
    container_name: dinkum-online-api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/usr/src/api/
    depends_on:
      - dinkum-online-db
  dinkum-online-db:
    image: mongo
    container_name: dinkum-online-db
    ports:
      - "27029:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}